using Content.Client.StorageMarket.EntitySystems;
using Content.Shared.StorageMarket.BUI;
using Content.Shared.StorageMarket.Entries;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketBuyTab : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ClientStorageMarketSystem _clientStorageMarketSystem;

    public event Action<StorageMarketStockUiEntry, int>? OnAddToCart;

    public StorageMarketBuyTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _clientStorageMarketSystem = _entityManager.System<ClientStorageMarketSystem>();
    }

    public void UpdateState(StorageMarketComputerInterfaceState state)
    {
        UpdateBuyStock(state);
    }

    private void UpdateBuyStock(StorageMarketComputerInterfaceState state)
    {
        BuyStock.RemoveAllChildren();

        foreach (var entry in state.Stock.Values)
        {
            if (!_clientStorageMarketSystem.TryGetVisuals(entry.Prototype, out var name, out var icon))
                continue;

            StorageMarketRowBuyStock row = new(entry, name, icon, _clientStorageMarketSystem.GetSinglePrice(entry));

            row.OnAddToCart += OnAddToCart;

            BuyStock.AddChild(row);
        }
    }
}