using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketRowSellCart : PanelContainer
{
    public StorageMarketRowSellCart()
    {
        RobustXamlLoader.Load(this);
    }
}