using Content.Shared.StorageMarket.Entries;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketRowSellCart : PanelContainer
{
    public StorageMarketSellCartUiEntry Entry;

    public StorageMarketRowSellCart(StorageMarketSellCartUiEntry entry, string name, Texture icon, int price)
    {
        RobustXamlLoader.Load(this);

        Entry = entry;
        Title.Text = name;
        Icon.Texture = icon;
        Price.Text = $"${price}";
    }
}