using Content.Shared.StorageMarket.Entries;
using Content.Shared.StorageMarket.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketRowBuyStock : PanelContainer
{
    public StorageMarketStockUiEntry Entry;

    public event Action<StorageMarketStockUiEntry, int>? OnAddToCart;

    public StorageMarketRowBuyStock(StorageMarketStockUiEntry entry, string name, Texture icon, int price)
    {
        RobustXamlLoader.Load(this);

        Entry = entry;
        Title.Text = name;
        Icon.Texture = icon;
        Price.Text = $"${price}";

        AddToCart1.OnPressed += args => OnAddToCart?.Invoke(entry, 1);
        AddToCart5.OnPressed += args => OnAddToCart?.Invoke(entry, 5);
        AddToCart10.OnPressed += args => OnAddToCart?.Invoke(entry, 10);
        AddToCart30.OnPressed += args => OnAddToCart?.Invoke(entry, 30);
        AddToCartAll.OnPressed += args => OnAddToCart?.Invoke(entry, entry.StockCount);

        AddToCart1.Visible = entry.StockCount >= 1;
        AddToCart5.Visible = entry.StockCount >= 5;
        AddToCart10.Visible = entry.StockCount >= 10;
        AddToCart30.Visible = entry.StockCount >= 30;
    }
}