using System.Diagnostics.CodeAnalysis;
using Content.Client.StorageMarket.EntitySystems;
using Content.Client.UserInterface.Controls;
using Content.Shared._NF.Market;
using Content.Shared.Stacks;
using Content.Shared.StorageMarket.BUI;
using Content.Shared.StorageMarket.Data;
using Content.Shared.StorageMarket.EntitySystems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ClientStorageMarketSystem _clientStorageMarketSystem;
    private readonly SpriteSystem _spriteSystem;

    public event Action? OnPurchaseCart;
    public event Action<StorageMarketStockUiEntry, int>? OnAddToCart;

    public StorageMarketMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _clientStorageMarketSystem = _entityManager.System<ClientStorageMarketSystem>();
        _spriteSystem = _entityManager.System<SpriteSystem>();

        PurchaseCart.OnPressed += args => OnPurchaseCart?.Invoke();
        SearchText.OnTextChanged += args => UpdateSearch();
        ClearSearchButton.OnPressed += args => SearchText.SetText(string.Empty);
    }

    private void UpdateSearch()
    {

    }

    public void UpdateState(StorageMarketComputerInterfaceState state)
    {
        UpdateBuyStock(state);
    }

    private void UpdateBuyStock(StorageMarketComputerInterfaceState state)
    {
        BuyStock.RemoveAllChildren();

        foreach (var entry in state.Stock.Values)
        {
            if (!_clientStorageMarketSystem.TryGetVisuals(entry.Prototype, out var name, out var icon))
                continue;

            StorageMarketRowBuyStock row = new(entry, name, icon, _clientStorageMarketSystem.GetSinglePrice(entry));

            row.OnAddToCart += OnAddToCart;

            BuyStock.AddChild(row);
        }
    }
}