using Content.Client.StorageMarket.EntitySystems;
using Content.Shared.StorageMarket.BUI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketSellTab : BoxContainer
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ClientStorageMarketSystem _clientStorageMarketSystem;

    public StorageMarketSellTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _clientStorageMarketSystem = _entityManager.System<ClientStorageMarketSystem>();
    }

    public void UpdateState(StorageMarketComputerInterfaceState state)
    {
        UpdateCart(state);
    }

    private void UpdateCart(StorageMarketComputerInterfaceState state)
    {
        Cart.RemoveAllChildren();

        foreach (var entry in state.SellCart)
        {
            if (!_clientStorageMarketSystem.TryGetVisuals(entry.Prototype, out var name, out var icon))
                continue;

            StorageMarketRowSellCart row = new(entry, name, icon, 0);

            Cart.AddChild(row);
        }
    }
}