using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketRowSellStock : PanelContainer
{
    public StorageMarketRowSellStock()
    {
        RobustXamlLoader.Load(this);
    }
}