using Content.Client.StorageMarket.EntitySystems;
using Content.Client.UserInterface.Controls;
using Content.Shared.StorageMarket.BUI;
using Content.Shared.StorageMarket.Data;
using Content.Shared.StorageMarket.Entries;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.StorageMarket.UI;

[GenerateTypedNameReferences]
public sealed partial class StorageMarketMenu : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _protoManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly ILocalizationManager _localizationManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly ClientStorageMarketSystem _clientStorageMarketSystem;
    private readonly SpriteSystem _spriteSystem;

    public event Action<StorageMarketStockUiEntry, int>? OnAddToCart;

    public event Action<StorageMarketMenuTab>? OnSetTab;

    public EntityUid Owner;

    public StorageMarketMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _clientStorageMarketSystem = _entityManager.System<ClientStorageMarketSystem>();
        _spriteSystem = _entityManager.System<SpriteSystem>();

        ButtonGroup tabGroup = new();

        BuyTabButton.Group = tabGroup;
        SellTabButton.Group = tabGroup;

        BuyTabButton.OnPressed += args => OnSetTab?.Invoke(StorageMarketMenuTab.Buy);
        SellTabButton.OnPressed += args => OnSetTab?.Invoke(StorageMarketMenuTab.Sell);

        UpdateState(new());
    }

    public void UpdateState(StorageMarketComputerInterfaceState state)
    {
        BuyTab.UpdateState(state);
        SellTab.UpdateState(state);
        SetVisibleTab(state.Tab);
    }

    private void SetVisibleTab(StorageMarketMenuTab tab)
    {
        BuyTab.Visible = tab == StorageMarketMenuTab.Buy;
        BuyTabButton.Pressed = BuyTab.Visible;

        SellTab.Visible = tab == StorageMarketMenuTab.Sell;
        SellTabButton.Pressed = SellTab.Visible;
    }
}